---
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  deploy:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            gem build 3scale_toolbox_copy_tenant_plugin.gemspec -o "3scale_toolbox_copy_tenant_plugin-$(git describe --tags).gem"
            gem push "3scale_toolbox_copy_tenant_plugin-$(git describe --tags).gem"
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
